apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spec.app.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.spec.app.port }}
    name: http
  selector:
    app: {{ .Values.spec.app.name }}